# Generated by Django 4.2.11 on 2024-03-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent1_name', models.CharField(max_length=100)),
                ('parent2_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('parenting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coparentbot.parentingplan')),
            ],
        ),
        migrations.CreateModel(
            name='DemeritPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parenting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coparentbot.parentingplan')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parenting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coparentbot.parentingplan')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('parenting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coparentbot.parentingplan')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_parent', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('parenting_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coparentbot.parentingplan')),
            ],
        ),
    ]
